name: E2E Regression Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  Chrome_Ubuntu_Test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Set up MySQL Server with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml up -d

      - name: Set up Selenium Grid with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml up --scale chrome=4 --scale edge=0 --scale firefox=0 -d

      - name: Check Running Containers
        run: docker ps

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="AddToCartTests.**"
          -DexecutionType="Remote"
          -DbrowserType="Chrome"
          -DisHeadless="true"
          -DsyncWithDB="true"
          -DparallelMode="NONE"
          -DthreadCount="4"

      - name: Upload allure-results file in Target Directory
        uses: actions/upload-artifact@v4
        with:
          name: target-allure-results-chrome_ubuntu
          path: target/allure-results

      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Chrome Ubuntu
          path: "target/site/allure-maven-plugin"

      - name: Cleanup Docker Containers
        if: always()
        run: |
          docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml down ; docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml down 


  Edge_Ubuntu_Test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Set up MySQL Server with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml up -d

      - name: Set up Selenium Grid with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml up --scale chrome=0 --scale edge=4 --scale firefox=0 -d

      - name: Check Running Containers
        run: docker ps

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="RegisterTests.**"
          -DexecutionType="Remote"
          -DbrowserType="Edge"
          -DisHeadless="true"
          -DsyncWithDB="true"
          -DparallelMode="NONE"
          -DthreadCount="4"

      - name: Upload allure-results file in Target Directory
        uses: actions/upload-artifact@v4
        with:
          name: target-allure-results-edge_ubuntu
          path: target/allure-results

      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Edge Ubuntu
          path: "target/site/allure-maven-plugin"

      - name: Cleanup Docker Containers
        if: always()
        run: |
          docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml down ; docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml down 

  Firefox_Ubuntu_Test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Set up MySQL Server with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml up -d

      - name: Set up Selenium Grid with Docker Containers
        run: docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml up --scale chrome=0 --scale edge=0 --scale firefox=7 -d

      - name: Check Running Containers
        run: docker ps

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="LoginTests.**"
          -DexecutionType="Remote"
          -DbrowserType="Firefox"
          -DisHeadless="true"
          -DsyncWithDB="true"
          -DparallelMode="NONE"
          -DthreadCount="6"

      - name: Upload allure-results file in Target Directory
        uses: actions/upload-artifact@v4
        with:
          name: target-allure-results-firefox_ubuntu
          path: target/allure-results

      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Firefox Ubuntu
          path: "target/site/allure-maven-plugin"

      - name: Cleanup Docker Containers
        if: always()
        run: |
          docker compose -f src/main/resources/dockerFiles/docker-compose-grid-v3.yml down ; docker compose -f src/main/resources/dockerFiles/docker-compose-mysql-v3.yml down 

  Chrome_Windows_Test:
    runs-on: windows-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="CheckoutTests.**"
          -DexecutionType="Local"
          -DbrowserType="Chrome"
          -DisHeadless="true"
          -DsyncWithDB="false"
          -DparallelMode="NONE"
          -DthreadCount="2"

      - name: Upload allure-results file in Target Directory
        uses: actions/upload-artifact@v4
        with:
          name: target-allure-results-chrome_windows
          path: target/allure-results

      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Chrome Windows
          path: "target/site/allure-maven-plugin"

  Edge_Windows_Test:
    runs-on: windows-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="ContactUsTests.**"
          -DexecutionType="Local"
          -DbrowserType="Edge"
          -DisHeadless="true"
          -DsyncWithDB="false"
          -DparallelMode="NONE"
          -DthreadCount="2"

      - name: Upload allure-results file in Target Directory
        uses: actions/upload-artifact@v4
        with:
          name: target-allure-results-edge_windows
          path: target/allure-results

      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Edge Windows
          path: "target/site/allure-maven-plugin"


  Firefox_Windows_Test:
    runs-on: windows-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="SearchProductTests.**"
          -DexecutionType="Local"
          -DbrowserType="Firefox"
          -DisHeadless="true"
          -DsyncWithDB="false"
          -DparallelMode="NONE"
          -DthreadCount="4"

      - name: Upload allure-results file in Target Directory
        uses: actions/upload-artifact@v4
        with:
          name: target-allure-results-firefox_windows
          path: target/allure-results

      - name: Generate Allure report
        run: mvn allure:report
      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Firefox Windows
          path: "target/site/allure-maven-plugin"

  Combine_Allure_Reports:
    runs-on: ubuntu-latest
    needs: [Chrome_Ubuntu_Test,Edge_Ubuntu_Test,Firefox_Ubuntu_Test,Chrome_Windows_Test,Edge_Windows_Test,Firefox_Windows_Test]
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Install Allure
        run: |
          # Download and unzip Allure
          curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/latest/download/allure-2.32.0.zip"
          unzip allure.zip
          sudo mv allure-2.32.0 /opt/allure  # Move the whole directory
          echo "/opt/allure/bin" >> $GITHUB_PATH  # Add Allure to the PATH

      # Download all Allure Files generated after every job
      - name: Download Allure results from Chrome Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: target-allure-results-chrome_ubuntu
          path: ./target-allure-results-chrome_ubuntu
        continue-on-error: true

      - name: Download Allure results from Edge Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: target-allure-results-edge_ubuntu
          path: ./target-allure-results-edge_ubuntu
        continue-on-error: true

      - name: Download Allure results from Firefox Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: target-allure-results-firefox_ubuntu
          path: ./target-allure-results-firefox_ubuntu
        continue-on-error: true

      - name: Download Allure results from Chrome Windows
        uses: actions/download-artifact@v4
        with:
          name: target-allure-results-chrome_windows
          path: ./target-allure-results-chrome_windows
        continue-on-error: true

      - name: Download Allure results from Edge Windows
        uses: actions/download-artifact@v4
        with:
          name: target-allure-results-edge_windows
          path: ./target-allure-results-edge_windows
        continue-on-error: true

      - name: Download Allure results from Firefox Windows
        uses: actions/download-artifact@v4
        with:
          name: target-allure-results-firefox_windows
          path: ./target-allure-results-firefox_windows
        continue-on-error: true

      # Combine all Allure Files of all Jobs into one directory
      - name: Combine Chrome Ubuntu Allure results into Combined Directory
        run: |
          mkdir -p ./allure-results
          cp -r ./target-allure-results-chrome_ubuntu/* ./allure-results/
        continue-on-error: true
      - name: Combine Edge Ubuntu Allure results into Combined Directory
        run: |
          mkdir -p ./allure-results
          cp -r ./target-allure-results-edge_ubuntu/* ./allure-results/
        continue-on-error: true
      - name: Combine Firefox Ubuntu Allure results into Combined Directory
        run: |
          mkdir -p ./allure-results
          cp -r ./target-allure-results-firefox_ubuntu/* ./allure-results/
        continue-on-error: true
      - name: Combine Chrome Windows Allure results into Combined Directory
        run: |
          mkdir -p ./allure-results
          cp -r ./target-allure-results-chrome_windows/* ./allure-results/
        continue-on-error: true
      - name: Combine Edge Windows Allure results into Combined Directory
        run: |
          mkdir -p ./allure-results
          cp -r ./target-allure-results-edge_windows/* ./allure-results/
        continue-on-error: true
      - name: Combine Firefox Windows Allure results into Combined Directory
        run: |
          mkdir -p ./allure-results
          cp -r ./target-allure-results-firefox_windows/* ./allure-results/
        continue-on-error: true

      # Generate the Allure Report from the Combined Directory
      - name: Generate Allure report
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat ./allure-report

      - name: Upload Combined Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Combined Allure Report
          path: ./allure-report
